version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: alinfo
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  tpAchatProject:
    depends_on:
      - mysqldb
    image: amineghanmi/tp-achat-back:latest
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/alinfo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": "P@ssw0rd",  
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true
    
    tpAchatProject-front:
    image: amineghanmi/tp-achatproject-front:latest
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - tpAchatProject

volumes:
  db:
